kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-scale-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "spectrum-scale"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
