kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scale-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: scale-provisioner-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: scale-provisioner-role
  apiGroup: rbac.authorization.k8s.io
